DROP TABLE IF EXISTS cities_of_ohio;

CREATE TABLE cities_of_ohio (
	city VARCHAR(22) NOT NULL, 
	population VARCHAR(7) NOT NULL, 
	county VARCHAR(60) NOT NULL, 
	UNIQUE (city)
);

INSERT INTO cities_of_ohio (city, population, county) VALUES ('Akron', '199,110', 'Summit County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Alliance', '22,322', 'Stark County and Mahoning County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Amherst', '12,021', 'Lorain County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Ashland', '20,362', 'Ashland County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Ashtabula', '19,124', 'Ashtabula County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Athens', '23,832', 'Athens County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Aurora', '15,548', 'Portage County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Avon', '21,193', 'Lorain County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Avon Lake', '22,581', 'Lorain County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Barberton', '26,550', 'Summit County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Bay Village', '15,651', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Beachwood', '11,953', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Beavercreek', '45,193', 'Greene County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Bedford', '13,074', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Bedford Heights', '10,751', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Bellbrook', '6,943', 'Greene County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Bellefontaine', '13,370', 'Logan County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Bellevue', '8,202', 'Huron County, Sandusky County, Erie County and Seneca County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Belpre', '6,441', 'Washington County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Berea', '19,093', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Bexley', '13,057', 'Franklin County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Blue Ash', '12,114', 'Hamilton County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Bowling Green', '30,028', 'Wood County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Brecksville', '13,656', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Broadview Heights', '19,400', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Brooklyn', '11,169', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Brook Park', '19,212', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Brookville', '5,884', 'Montgomery County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Brunswick', '34,255', 'Medina County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Bryan', '8,545', 'Williams County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Bucyrus', '12,362', 'Crawford County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Cambridge', '10,635', 'Guernsey County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Campbell', '8,235', 'Mahoning County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Canal Fulton', '5,479', 'Stark County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Canal Winchester', '7,101', 'Franklin County and Fairfield County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Canfield', '7,515', 'Mahoning County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Canton', '73,007', 'Stark County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Celina', '10,400', 'Mercer County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Centerville', '23,999', 'Montgomery County and Greene County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Chardon', '5,148', 'Geauga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Cheviot', '8,375', 'Hamilton County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Chillicothe', '21,901', 'Ross County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Cincinnati', '296,943', 'Hamilton County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Circleville', '13,314', 'Pickaway County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Clayton', '13,209', 'Montgomery County and Miami County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Cleveland', '396,815', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Cleveland Heights', '46,121', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Clyde', '6,325', 'Sandusky County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Columbiana', '6,384', 'Columbiana County and Mahoning County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Columbus', '787,033', 'Franklin County, Delaware County and Fairfield County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Conneaut', '12,841', 'Ashtabula County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Cortland', '7,104', 'Trumbull County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Coshocton', '11,216', 'Coshocton County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Cuyahoga Falls', '49,652', 'Summit County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Dayton', '141,527', 'Montgomery County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Deer Park', '5,736', 'Hamilton County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Defiance', '16,494', 'Defiance County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Delaware', '34,753', 'Delaware County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Delphos', '7,101', 'Allen County and Van Wert County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Dover', '12,826', 'Tuscarawas County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Dublin', '41,751', 'Franklin County, Delaware County and Union County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('East Cleveland', '17,843', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('East Liverpool', '11,195', 'Columbiana County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Eastlake', '18,577', 'Lake County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Eaton', '8,407', 'Preble County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Elyria', '54,533', 'Lorain County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Englewood', '13,465', 'Montgomery County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Euclid', '48,920', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Fairborn', '32,352', 'Greene County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Fairfield', '42,510', 'Butler County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Fairlawn', '7,437', 'Summit County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Fairview Park', '16,826', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Findlay', '41,202', 'Hancock County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Forest Park', '18,720', 'Hamilton County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Fostoria', '13,441', 'Seneca County, Hancock County and Wood County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Franklin', '11,771', 'Warren County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Fremont', '16,734', 'Sandusky County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Gahanna', '33,248', 'Franklin County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Galion', '10,512', 'Crawford County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Garfield Heights', '28,849', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Geneva', '6,215', 'Ashtabula County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Germantown', '6,215', 'Montgomery County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Girard', '9,958', 'Trumbull County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Grandview Heights', '6,536', 'Franklin County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Green', '25,699', 'Summit County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Greenville', '13,227', 'Darke County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Grove City', '35,575', 'Franklin County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Groveport', '5,363', 'Franklin County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Hamilton', '62,477', 'Butler County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Harrison', '9,897', 'Hamilton County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Heath', '10,310', 'Licking County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Highland Heights', '8,345', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Hilliard', '28,435', 'Franklin County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Hillsboro', '6,605', 'Highland County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Hubbard', '7,874', 'Trumbull County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Huber Heights', '38,101', 'Montgomery County and Miami County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Hudson', '22,262', 'Summit County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Huron', '7,149', 'Erie County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Independence', '7,133', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Ironton', '11,129', 'Lawrence County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Jackson', '6,397', 'Jackson County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Kent', '28,904', 'Portage County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Kenton', '8,262', 'Hardin County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Kettering', '56,163', 'Montgomery County and Greene County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Kirtland', '6,866', 'Lake County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Lakewood', '52,131', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Lancaster', '38,780', 'Fairfield County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Lebanon', '20,033', 'Warren County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Lima', '38,771', 'Allen County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Logan', '7,152', 'Hocking County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('London', '9,904', 'Madison County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Lorain', '64,097', 'Lorain County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Louisville', '9,186', 'Stark County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Loveland', '12,081', 'Hamilton County, Clermont County and Warren County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Lyndhurst', '14,001', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Macedonia', '11,188', 'Summit County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Madeira', '8,726', 'Hamilton County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Mansfield', '47,821', 'Richland County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Maple Heights', '23,138', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Marietta', '14,085', 'Washington County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Marion', '36,837', 'Marion County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Martins Ferry', '6,915', 'Belmont County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Marysville', '22,094', 'Union County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Mason', '30,712', 'Warren County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Massillon', '32,149', 'Stark County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Maumee', '14,286', 'Lucas County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Mayfield Heights', '19,155', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Medina', '26,678', 'Medina County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Mentor', '47,159', 'Lake County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Mentor-on-the-Lake', '7,443', 'Lake County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Miamisburg', '20,181', 'Montgomery County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Middleburg Heights', '15,946', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Middletown', '48,694', 'Butler County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Milford', '6,709', 'Clermont County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Monroe', '12,442', 'Butler County and Warren County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Montgomery', '10,251', 'Hamilton County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Moraine', '6,307', 'Montgomery County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Mount Healthy', '6,098', 'Hamilton County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Mount Vernon', '16,990', 'Knox County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Munroe Falls', '5,012', 'Summit County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Napoleon', '8,749', 'Henry County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Nelsonville', '5,392', 'Athens County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('New Albany', '7,724', 'Franklin County and Licking County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('New Carlisle', '5,785', 'Clark County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('New Franklin', '14,227', 'Summit County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('New Philadelphia', '17,288', 'Tuscarawas County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Newark', '47,573', 'Licking County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Niles', '19,266', 'Trumbull County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('North Canton', '17,488', 'Stark County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('North College Hill', '9,397', 'Hamilton County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('North Olmsted', '32,718', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('North Ridgeville', '29,465', 'Lorain County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('North Royalton', '30,444', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Northwood', '5,265', 'Wood County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Norton', '12,085', 'Summit County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Norwalk', '17,012', 'Huron County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Norwood', '19,207', 'Hamilton County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Oakwood', '9,202', 'Montgomery County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Oberlin', '8,286', 'Lorain County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Olmsted Falls', '9,024', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Ontario', '6,225', 'Richland County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Oregon', '20,291', 'Lucas County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Orrville', '8,380', 'Wayne County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Oxford', '21,371', 'Butler County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Painesville', '19,563', 'Lake County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Parma', '81,601', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Parma Heights', '20,718', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Pataskala', '14,962', 'Licking County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Pepper Pike', '5,979', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Perrysburg', '20,623', 'Wood County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Pickerington', '18,291', 'Fairfield County and Franklin County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Piqua', '20,522', 'Miami County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Port Clinton', '6,056', 'Ottawa County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Portsmouth', '20,226', 'Scioto County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Powell', '11,500', 'Delaware County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Ravenna', '11,724', 'Portage County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Reading', '10,385', 'Hamilton County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Reynoldsburg', '35,893', 'Franklin County, Fairfield County and Licking County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Richmond Heights', '10,546', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Rittman', '6,491', 'Wayne County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Riverside', '25,201', 'Montgomery County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Rocky River', '20,213', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Rossford', '6,293', 'Wood County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('St. Clairsville', '5,184', 'Belmont County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('St. Marys', '8,332', 'Auglaize County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Salem', '12,303', 'Columbiana County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Sandusky', '25,793', 'Erie County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Seven Hills', '11,804', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Shaker Heights', '28,448', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Sharonville', '13,560', 'Hamilton County and Butler County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Sheffield Lake', '9,137', 'Lorain County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Shelby', '9,317', 'Richland County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Sidney', '21,229', 'Shelby County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Solon', '23,348', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('South Euclid', '22,295', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Springboro', '17,409', 'Warren County and Montgomery County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Springdale', '11,223', 'Hamilton County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Springfield', '60,608', 'Clark County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Steubenville', '18,659', 'Jefferson County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Stow', '34,837', 'Summit County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Streetsboro', '16,028', 'Portage County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Strongsville', '44,750', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Struthers', '10,713', 'Mahoning County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Sylvania', '18,965', 'Lucas County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Tallmadge', '17,537', 'Summit County and Portage County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Tiffin', '17,963', 'Seneca County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Tipp City', '9,689', 'Miami County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Toledo', '287,208', 'Lucas County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Toronto', '5,091', 'Jefferson County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Trenton', '11,869', 'Butler County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Trotwood', '24,431', 'Montgomery County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Troy', '25,058', 'Miami County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Twinsburg', '18,795', 'Summit County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Uhrichsville', '5,413', 'Tuscarawas County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Union', '6,419', 'Montgomery County and Miami County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('University Heights', '13,539', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Upper Arlington', '33,771', 'Franklin County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Upper Sandusky', '6,596', 'Wyandot County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Urbana', '11,793', 'Champaign County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Van Wert', '10,846', 'Van Wert County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Vandalia', '15,246', 'Montgomery County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Vermilion', '10,594', 'Lorain County and Erie County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Wadsworth', '21,567', 'Medina County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Wapakoneta', '9,867', 'Auglaize County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Waterville', '5,523', 'Lucas County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Warren', '41,557', 'Trumbull County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Warrensville Heights', '13,542', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Washington Court House', '14,192', 'Fayette County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Wauseon', '7,332', 'Fulton County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Wellston', '5,663', 'Jackson County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('West Carrollton', '13,143', 'Montgomery County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Westerville', '36,120', 'Franklin County and Delaware County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Westlake', '32,729', 'Cuyahoga County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Whitehall', '18,062', 'Franklin County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Wickliffe', '12,750', 'Lake County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Willard', '6,236', 'Huron County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Willoughby', '22,268', 'Lake County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Willoughby Hills', '9,485', 'Lake County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Willowick', '14,171', 'Lake County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Wilmington', '12,520', 'Clinton County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Wooster', '26,119', 'Wayne County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Worthington', '13,575', 'Franklin County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Wyoming', '8,428', 'Hamilton County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Xenia', '25,719', 'Greene County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Youngstown', '66,982', 'Mahoning County');
INSERT INTO cities_of_ohio (city, population, county) VALUES ('Zanesville', '25,487', 'Muskingum County');
